name: sofia
description: AI powered yoga instructor

publish_to: "none"

;version: 0.4.0+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+3
  websafe_svg: ^1.1.0
  font_awesome_flutter: ^8.8.1
  flutter_tts: ^1.2.2
  tflite: ^1.1.1
  showcaseview: ^0.1.5
  camera: ^0.6.2+1
  video_player: ^1.0.0
  google_fonts: ^1.1.1
  # flutter_statusbarcolor: ^0.2.3
  flare_flutter: ^2.0.6
  flutter_riverpod: ^0.12.4
  json_annotation: ^3.1.1
  simple_animations: ^2.5.1
  supercharged: ^1.12.0
  cached_network_image: ^2.5.1
  wakelock: ^0.2.1+1
  dialog_flowtter: ^0.2.0
  audioplayers: ^0.17.4
  speech_to_text: ^3.2.0
  animated_text_kit: ^3.1.2
  avatar_glow: ^1.2.0
  audiofileplayer: ^1.3.3
  flutter_statusbarcolor: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.12.7
  build_runner: ^1.11.1
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: fonts/Montserrat-Bold.ttf
          weight: 600

    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
          weight: 300
        - asset: fonts/GoogleSans-Medium.ttf
          weight: 400
        - asset: fonts/GoogleSans-Bold.ttf
          weight: 600

    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
          weight: 300

    - family: LexendTera
      fonts:
        - asset: fonts/LexendTera-Regular.ttf
          weight: 300

  assets:
    - assets/images/
    - assets/rive/
    - assets/tflite/
    - assets/dialogflow/
